$(document).ready(function(){
    var classes = ["aden",
                  "reyes",
                  "perpetua",
                  "inkwell",
                  "toaster",
                  "walden",
                  "hudson",
                  "gingham",
                  "mayfair",
                  "lofi",
                  "xpro2",
                  "_1977",
                  "brooklyn",
                  "nashville",
                  "lark",
                  "moon",
                  "clarendon",
                  "willow"];
    $("#tot").each(function(){
        $(this).addClass(classes[~~(Math.random()*classes.length)]);
    });
});
